# Generated by Django 5.0.4 on 2024-04-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUserFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('not_followed_back', models.TextField(blank=True)),
                ('not_following_back', models.TextField(blank=True)),
                ('mutual_list', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUserPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('posts_count', models.IntegerField(default=0)),
                ('most_liked_post', models.CharField(blank=True, max_length=255)),
                ('most_commented_post', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(auto_created=True)),
                ('user', models.CharField(max_length=255)),
                ('profile_pic_link', models.CharField(max_length=255)),
                ('country', models.CharField(default=None, max_length=255)),
                ('biography', models.CharField(default=None, max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('full_name', models.CharField(default=None, max_length=255)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('followers_list', models.TextField(blank=True)),
                ('following_list', models.TextField(blank=True)),
            ],
        ),
    ]
