# Generated by Django 5.0.4 on 2024-04-29 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUserFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_following_but_not_followed_list', models.TextField(blank=True)),
                ('user_followed_but_not_following_list', models.TextField(blank=True)),
                ('mutual_lıst', models.TextField(blank=True)),
                ('follower_who_liked_the_most_posts', models.CharField(blank=True, max_length=255)),
                ('follower_who_commented_the_most_post', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.instagramuser')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUserPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_count', models.IntegerField(default=0)),
                ('posts_list', models.TextField(blank=True)),
                ('most_liked_post', models.CharField(blank=True, max_length=255)),
                ('most_commented_post', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.instagramuser')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateTimeField(auto_created=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('followers_list', models.TextField(blank=True)),
                ('following_list', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.instagramuser')),
            ],
        ),
    ]
