# Generated by Django 5.0.4 on 2024-04-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_instagramuserfriends_instagramuserposts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuserprofile',
            name='biography',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='instagramuserprofile',
            name='country',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='instagramuserprofile',
            name='full_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='instagramuserprofile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instagramuserprofile',
            name='profile_pic_link',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
