# Generated by Django 5.0.4 on 2024-04-29 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_instagramuserprofile_biography_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramuserfriends',
            old_name='mutual_lıst',
            new_name='mutual_list',
        ),
        migrations.RemoveField(
            model_name='instagramuserfriends',
            name='follower_who_commented_the_most_post',
        ),
        migrations.RemoveField(
            model_name='instagramuserfriends',
            name='follower_who_liked_the_most_posts',
        ),
    ]
