# Generated by Django 5.0.4 on 2024-04-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_rename_mutual_lıst_instagramuserfriends_mutual_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuserposts',
            name='posts_list',
        ),
    ]
