# Generated by Django 5.0.4 on 2024-04-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_remove_instagramuserposts_posts_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuserfriends',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instagramuserposts',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instagramuserprofile',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
