# Generated by Django 5.0.4 on 2024-04-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_alter_instagramuserfriends_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramuserfriends',
            old_name='user_followed_but_not_following_list',
            new_name='not_followed_back',
        ),
        migrations.RenameField(
            model_name='instagramuserfriends',
            old_name='user_following_but_not_followed_list',
            new_name='not_following_back',
        ),
    ]
