# Generated by Django 5.0.4 on 2024-04-30 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_rename_user_followed_but_not_following_list_instagramuserfriends_not_followed_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuserfriends',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.instagramuserprofile'),
        ),
        migrations.AlterField(
            model_name='instagramuserposts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insta.instagramuserprofile'),
        ),
    ]
