# Generated by Django 5.0.4 on 2024-04-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_alter_instagramuserfriends_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuserfriends',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='instagramuserposts',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
